/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.app;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Statement;

/**
 *
 * @author Owner
 */
public class EmployeeDetails extends javax.swing.JFrame {
Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form EmployeeDetails
     */
    public EmployeeDetails() {
        initComponents();
        con=Connect.getConnection();
        setLocationRelativeTo(null);
        this.setSize(424, 569);
        this.setLocation(350,50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Employee Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(34, 29, 206, 29);

        jLabel2.setText("Employee ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(34, 92, 71, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(123, 89, 150, 22);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(34, 140, 59, 25);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(280, 140, 73, 25);

        jLabel3.setText("Employee ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(34, 181, 71, 16);

        jLabel4.setText("Employee Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(34, 210, 92, 16);

        jLabel5.setText("NIC No.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(34, 239, 43, 16);

        jLabel6.setText("Gender");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(34, 268, 41, 16);

        jLabel7.setText("Address");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(34, 297, 46, 16);

        jLabel8.setText("Employee Type");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(34, 326, 87, 16);

        jLabel9.setText("Contact No.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(36, 380, 80, 20);

        jLabel10.setText("Salary");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 410, 36, 16);

        jLabel11.setText("Attendance");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(40, 440, 80, 16);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField2.setEnabled(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(158, 178, 175, 22);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField3.setEnabled(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(158, 207, 175, 22);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField4.setEnabled(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(158, 236, 175, 22);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField5.setEnabled(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(158, 265, 175, 22);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField6.setEnabled(false);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(158, 294, 175, 22);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField7.setEnabled(false);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(158, 323, 175, 22);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField8.setToolTipText("");
        jTextField8.setEnabled(false);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(160, 380, 175, 22);

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField9.setEnabled(false);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(160, 410, 175, 22);

        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jTextField10);
        jTextField10.setBounds(160, 440, 175, 22);

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(150, 140, 65, 25);

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(160, 490, 73, 25);

        jLabel13.setText("Specialized Branch");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 350, 120, 30);

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11);
        jTextField11.setBounds(159, 352, 174, 22);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/app/employee1.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-290, -70, 760, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Reset(){
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField7.setText("");
    jTextField8.setText("");
    jTextField9.setText("");
    jTextField10.setText("");
    jTextField11.setText("");
    jButton4.setEnabled(true);
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  this.setVisible(false);
  new MainPageGUI().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Reset();
try{
    con=Connect.getConnection();
    if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter employee id","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    Statement stmt;
    stmt=con.createStatement();
    String sql1="Select * from employee where E_ID='"+jTextField1.getText() + "'";
    pst=con.prepareStatement(sql1);
    rs=pst.executeQuery();
    if(rs.next()){
        this.setVisible(true);
        String add1=rs.getString("E_ID");
        this.jTextField2.setText(add1);
        String add2=rs.getString("E_NAME");
        this.jTextField3.setText(add2);
        String add3=rs.getString("NIC");
        this.jTextField4.setText(add3);
        String add4=rs.getString("GENDER");
        this.jTextField5.setText(add4);
        String add5=rs.getString("ADDRESS");
        this.jTextField6.setText(add5);
        String add6=rs.getString("E_TYPE");
        this.jTextField7.setText(add6);
        String add7=rs.getString("CONTACT_NO");
        this.jTextField8.setText(add7);
        String add8=rs.getString("SALARY");
        String add9=rs.getString("ATTENDANCE");
        this.jTextField10.setText(add9);
        double salary=Double.parseDouble(add8)*Double.parseDouble(add9);
        String add10=Double.toString(salary);
        this.jTextField9.setText(add10);
        String add11=rs.getString("SPECIALIST");
        this.jTextField11.setText(add11);
    }
    
}catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Reset();
jTextField1.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try{
    con=Connect.getConnection();
    if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter employee id","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    Statement stmt;
    stmt=con.createStatement();
    String sql2="Select E_ID from employee where E_ID='"+jTextField1.getText() + "'";
    rs=stmt.executeQuery(sql2);
    String sql="update employee set ATTENDANCE ='"+jTextField10.getText()+"', T_SALARY='"+jTextField9.getText()+"', SPECIALIST='"+jTextField11.getText()+"'where E_ID='"+jTextField1.getText() + "'";
    pst=con.prepareStatement(sql);
    pst.execute();
    jButton4.setEnabled(false);
    JOptionPane.showMessageDialog(this,"Successfully saved","Employee Record",JOptionPane.INFORMATION_MESSAGE);
    jButton4.setEnabled(true);
    }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);    
    
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
