/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.app;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
/**
 *
 * @author Owner
 */
public class PatientAdmit extends javax.swing.JFrame {
Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form PatientAdmit
     */
    public PatientAdmit() {
        initComponents();
        setLocationRelativeTo(null);
        this.setSize(400, 450);
        this.setLocation(350,50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Patient Info");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(48, 26, 144, 29);

        jLabel2.setText("Patient ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(48, 71, 55, 16);

        jLabel3.setText("Patient Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(48, 106, 76, 16);

        jLabel4.setText("Gender");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(48, 141, 41, 16);

        jLabel5.setText("Address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(48, 176, 46, 16);

        jLabel6.setText("Date Admitted");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(48, 211, 81, 16);

        jLabel7.setText("Recommended Doctor");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(48, 243, 126, 16);

        jLabel8.setText("Contact No.");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(50, 270, 66, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(186, 68, 150, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(186, 103, 150, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jComboBox1.setSelectedIndex(-1);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(186, 138, 150, 22);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(186, 173, 150, 22);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(186, 208, 80, 22);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(186, 240, 150, 22);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(186, 275, 150, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("(YYYY/MM/DD)");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(270, 210, 104, 16);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(90, 352, 59, 25);

        jButton2.setText("New");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(179, 352, 57, 25);

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(263, 352, 73, 25);

        jLabel10.setText("Consultant Doctor ID");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(50, 300, 120, 20);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(186, 304, 150, 22);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/app/patientBed.jpg"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-40, -20, 450, 520);
        jLabel12.getAccessibleContext().setAccessibleName("jLabel11");

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Reset(){/*reset*/
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField7.setText("");
    jComboBox1.setSelectedIndex(-1);
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    Reset();/*reset*/
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
    con=Connect.getConnection();    
    if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter patient id","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    if (jTextField2.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter patient name","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    if (jTextField3.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter address","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    if (jTextField4.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter date admitted","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    if (jComboBox1.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog( this, "Please select gender","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    if (jTextField5.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter recommended doctor","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    if (jTextField6.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter contact no.","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }/*empty textboxes*/
    Statement stmt;
    stmt=con.createStatement();
    /*selecting the table*/
    String sql2="Select P_ID from patient where P_ID='"+jTextField1.getText() + "'";
    rs=stmt.executeQuery(sql2);
    if(rs.next()){/*checking for same ID*/
        JOptionPane.showMessageDialog( this, "Patient ID already exists","Error", JOptionPane.ERROR_MESSAGE);
        jTextField1.setText("");
        return;
    }
    /*creating a new patient*/
    String sql="insert into patient(P_ID, GENDER, NAME, ADDRESS, DATE_ADDED, RECOMMENDATION, CONTACT_NO) values('"+jTextField1.getText()+"','"+jComboBox1.getSelectedItem()+ "','"+jTextField2.getText()+"','"+jTextField3.getText()+"','"+jTextField4.getText()+"','"+jTextField5.getText()+"','"+jTextField6.getText()+"')";
    pst=con.prepareStatement(sql);
    pst.execute();
    
    String sql3= "insert into patient_treatments(P_ID, CONSUL_ID)values('"+ jTextField1.getText() + "','"+ jTextField7.getText() + "')";
    pst=con.prepareStatement(sql3);
    pst.execute();
    JOptionPane.showMessageDialog(this,"Successfully saved","Patient Record",JOptionPane.INFORMATION_MESSAGE);
    jButton3.setEnabled(false);
}catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);    
    
}    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  this.setVisible(false);
  new MainPageGUI().setVisible(true);/*back*/
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientAdmit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientAdmit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientAdmit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientAdmit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientAdmit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
