/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.app;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class PatientBill extends javax.swing.JFrame {
Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form PatientBill
     */
    public PatientBill() {
        initComponents();
        setLocationRelativeTo(null);
        this.setSize(820, 540);
        this.setLocation(350,50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField18 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Patient Info");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 13, 144, 29);

        jLabel2.setText("Patient ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 53, 71, 16);

        jLabel3.setText("Patient Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 81, 89, 16);

        jLabel4.setText("Treatments");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(12, 110, 76, 16);

        jLabel5.setText("Results");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 159, 56, 16);

        jLabel6.setText("Adimt Date");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(12, 216, 76, 16);

        jLabel7.setText("Ward ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(12, 245, 76, 16);

        jLabel8.setText("Ward Type");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(12, 274, 97, 16);

        jLabel9.setText("Consultant Doctor ID");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(12, 303, 136, 16);

        jLabel10.setText("Additional Consultant ID");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(12, 332, 144, 16);

        jLabel11.setText("Discharge Date");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(12, 361, 100, 16);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Payment Details");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(466, 13, 195, 29);

        jLabel13.setText("Bed Charge");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(466, 52, 77, 16);

        jLabel14.setText("No. of Days");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(466, 81, 77, 16);

        jLabel15.setText("Total Bed Charges");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(466, 110, 119, 16);

        jLabel16.setText("Service Charge");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(466, 139, 100, 16);

        jLabel17.setText("Billing Date");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(466, 168, 79, 16);

        jLabel18.setText("Payment Mode");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(466, 252, 100, 16);

        jLabel19.setText("Payment Details");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(466, 281, 100, 16);

        jLabel20.setText("Total Charges");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(466, 310, 92, 16);

        jLabel21.setText("Total Paid");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(466, 339, 73, 16);

        jLabel22.setText("Due Charges");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(466, 365, 92, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(174, 50, 125, 22);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField2.setEnabled(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(174, 81, 200, 22);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(174, 110, 200, 40);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(174, 159, 200, 47);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField3.setEnabled(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(174, 213, 125, 22);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField4.setEnabled(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(174, 242, 200, 22);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField5.setEnabled(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(174, 271, 200, 22);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField6.setEnabled(false);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(174, 300, 200, 22);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField7.setEnabled(false);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(174, 329, 200, 22);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(174, 358, 125, 22);

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField9.setEnabled(false);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(603, 49, 150, 22);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(603, 78, 150, 22);

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField11.setEnabled(false);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(603, 107, 150, 22);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(603, 136, 150, 22);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(603, 165, 150, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Credit/Debit Card", "Cheque" }));
        jComboBox1.setSelectedIndex(-1);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(603, 249, 150, 22);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(603, 278, 150, 22);

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField15.setEnabled(false);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(603, 307, 150, 22);
        getContentPane().add(jTextField16);
        jTextField16.setBounds(603, 336, 150, 22);

        jTextField17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField17.setEnabled(false);
        getContentPane().add(jTextField17);
        jTextField17.setBounds(603, 365, 150, 22);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(306, 49, 73, 25);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(315, 400, 59, 25);

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(386, 400, 73, 25);

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(477, 400, 65, 25);
        getContentPane().add(jTextField18);
        jTextField18.setBounds(603, 193, 150, 22);

        jLabel23.setText("Treatment charges");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(466, 196, 109, 16);

        jTextField19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField19.setEnabled(false);
        getContentPane().add(jTextField19);
        jTextField19.setBounds(603, 222, 150, 22);

        jLabel24.setText("Payment Mode");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(466, 225, 84, 16);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/app/medical-hallway.jpg"))); // NOI18N
        getContentPane().add(jLabel25);
        jLabel25.setBounds(0, -40, 830, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Reset(){
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField7.setText("");
    jTextField8.setText("");
    jTextField9.setText("");    
    jTextField10.setText("");    
    jTextField11.setText("");
    jTextField12.setText("");
    jTextField13.setText("");
    jTextField14.setText("");
    jTextField15.setText("");
    jTextField16.setText("");
    jTextField17.setText("");
    jTextField18.setText("");
    jTextField19.setText("");
    jTextArea1.setText("");
    jTextArea2.setText("");
    jComboBox1.setSelectedIndex(-1);
    jButton3.setEnabled(true);
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.setVisible(false);
new MainPageGUI().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Reset();
try{
    con=Connect.getConnection();
    if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter patient id","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    Statement stmt;
    stmt=con.createStatement();
    String sql1="Select * from patient where P_ID='"+jTextField1.getText() + "'";
    pst=con.prepareStatement(sql1);
    rs=pst.executeQuery();
    if(rs.next()){
        this.setVisible(true);
        String add1=rs.getString("NAME");
        this.jTextField2.setText(add1);
        String add2=rs.getString("DATE_ADDED");
        this.jTextField3.setText(add2);
        String add3=rs.getString("W_ID");
        this.jTextField4.setText(add3);
        String add4=rs.getString("DATE_DISCHARGED");
        this.jTextField8.setText(add4);
    }
    
    String sql2="Select * from patient_treatments where P_ID='"+jTextField1.getText() + "'";
    pst=con.prepareStatement(sql2);
    rs=pst.executeQuery();
    if(rs.next()){
        this.setVisible(true);
        String add1=rs.getString("TESTS");
        this.jTextArea1.setText(add1);
        this.setVisible(true);
        String add2=rs.getString("RESULTS");
        this.jTextArea2.setText(add2);
        this.setVisible(true);
        String add3=rs.getString("CONSUL_ID");
        this.jTextField6.setText(add3);
        this.setVisible(true);
        String add4=rs.getString("ADD_CONSUL_ID");
        this.jTextField7.setText(add4);
    }
    String sql3="Select * from ward where W_ID='"+jTextField4.getText() + "'";
    pst=con.prepareStatement(sql3);
    rs=pst.executeQuery();
    if(rs.next()){
        this.setVisible(true);
        String add1=rs.getString("W_TYPE");
        this.jTextField5.setText(add1);
        String add2=rs.getString("B_CHARGE");
        this.jTextField9.setText(add2);
    }
    String sql4="Select * from payment where P_ID='"+jTextField1.getText() + "'";
    pst=con.prepareStatement(sql4);
    rs=pst.executeQuery();
    if(rs.next()){
        this.setVisible(true);
        String add1=rs.getString("W_DAYS");
        this.jTextField10.setText(add1);
        double bed_charge=Double.parseDouble(add1)*Double.parseDouble(jTextField9.getText());
        String add2=Double.toString(bed_charge);
        this.jTextField11.setText(add2);
        String add3=rs.getString("S_CHARGE");
        this.jTextField12.setText(add3);
        String add4=rs.getString("B_DATE");
        this.jTextField13.setText(add4);
        String add5=rs.getString("TR_CHARGE");
        this.jTextField18.setText(add5);
        String add6=rs.getString("P_MODE");
        this.jTextField19.setText(add6);
        String add7=rs.getString("P_DETAILS");
        this.jTextField14.setText(add7);
        double total=Double.parseDouble(add2)+Double.parseDouble(add3)+Double.parseDouble(add5);
        String add8=Double.toString(total);
        this.jTextField15.setText(add8);
        String add9=rs.getString("T_PAID");
        this.jTextField16.setText(add9);
        if (jTextField16.getText().equals("")) {
            this.jTextField17.setText("");
        }
        else{
            double due=Double.parseDouble(add8)-Double.parseDouble(add9);
            String add10=Double.toString(due);
            this.jTextField17.setText(add10);
        }
    }
    
    }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    Reset();
    jTextField1.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
    con=Connect.getConnection();
    if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter patient id","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    Statement stmt;
    stmt=con.createStatement();
    String sql1="Select P_ID from patient where P_ID='"+jTextField1.getText() + "'";
    rs=stmt.executeQuery(sql1);
    String sql="update patient set DATE_DISCHARGED ='"+jTextField8.getText()+"'where P_ID='"+jTextField1.getText() + "'";
    pst=con.prepareStatement(sql);
    pst.execute();
    String sql2="Select P_ID from payment where P_ID='"+jTextField1.getText() + "'";
    rs=stmt.executeQuery(sql2);
    if(rs.next()){
        String sql3="update payment set W_DAYS ='"+jTextField10.getText()+"', S_CHARGE='"+jTextField12.getText()+"', B_DATE='"+jTextField13.getText()+"', TR_CHARGE='"+jTextField18.getText()+"', P_MODE='"+jComboBox1.getSelectedItem()+"', P_DETAILS='"+jTextField14.getText()+"', TOTAL='"+jTextField15.getText()+"', T_PAID='"+jTextField16.getText()+"'where P_ID='"+jTextField1.getText() + "'";
        pst=con.prepareStatement(sql3);
        pst.execute();
        if (jTextField17.getText().equals("")) {
            jButton3.setEnabled(false);
            JOptionPane.showMessageDialog(this,"Successfully saved","Payment Record",JOptionPane.INFORMATION_MESSAGE);           

        }
        else{
            String sql5="update payment set DUE='"+ jTextField17.getText() + "'where P_ID='"+jTextField1.getText() + "'";
            pst=con.prepareStatement(sql5);
            pst.execute();
            jButton3.setEnabled(false);
            JOptionPane.showMessageDialog(this,"Successfully saved","Payment Record",JOptionPane.INFORMATION_MESSAGE);           
            jButton3.setEnabled(true);
        }
    }
    double bed_charge=Double.parseDouble(jTextField10.getText())*Double.parseDouble(jTextField9.getText());
    String add2=Double.toString(bed_charge);
    this.jTextField11.setText(add2);
    double total=Double.parseDouble(jTextField9.getText())*Double.parseDouble(jTextField10.getText())+Double.parseDouble(jTextField12.getText())+Double.parseDouble(jTextField18.getText());
    String add8=Double.toString(total);
    this.jTextField15.setText(add8);
    double due=Double.parseDouble(jTextField15.getText())-Double.parseDouble(jTextField16.getText());
    String add10=Double.toString(due);
    this.jTextField17.setText(add10);
    
    }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);    
    
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
