/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.app;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Statement;
/**
 *
 * @author Owner
 */
public class PatientDetails extends javax.swing.JFrame {
Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form PatientDetails
     */
    public PatientDetails() {
        initComponents();
        con=Connect.getConnection();
        setLocationRelativeTo(null);
        this.setSize(464, 750);
        this.setLocation(350,50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        textArea1 = new java.awt.TextArea();
        textArea2 = new java.awt.TextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Patient Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(36, 30, 175, 29);

        jLabel2.setText("Patient ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 55, 16);

        jLabel3.setText("Patient ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(36, 195, 55, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(180, 80, 150, 22);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 140, 59, 25);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(270, 140, 73, 25);

        jLabel4.setText("Patient Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(36, 224, 76, 16);

        jLabel5.setText("Gender");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(36, 253, 41, 16);

        jLabel6.setText("Address");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(36, 282, 46, 16);

        jLabel7.setText("Date Added");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(36, 311, 66, 16);

        jLabel8.setText("Date Discharged");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(36, 340, 93, 16);

        jLabel9.setText("Recommended Doctor");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(36, 369, 126, 16);

        jLabel10.setText("Contact No.");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(36, 398, 66, 16);

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField2.setEnabled(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(180, 192, 175, 22);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField3.setEnabled(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(180, 221, 175, 22);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField4.setEnabled(false);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(180, 250, 175, 22);

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField5.setEnabled(false);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(180, 279, 175, 22);

        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField6.setEnabled(false);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(180, 308, 125, 22);

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        getContentPane().add(jTextField7);
        jTextField7.setBounds(180, 337, 125, 22);

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField8.setEnabled(false);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(180, 366, 175, 22);

        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jTextField9.setEnabled(false);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(180, 395, 175, 22);

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(180, 660, 73, 25);

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(150, 140, 65, 25);

        jLabel11.setText("Tests");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(36, 427, 60, 16);

        jLabel12.setText("Results");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(36, 498, 70, 16);

        jLabel13.setText("Consultant Doctor ID");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(36, 573, 130, 16);

        jLabel14.setText("Additional Doctor ID");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(36, 601, 130, 16);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(180, 569, 175, 22);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(180, 598, 175, 22);
        getContentPane().add(textArea1);
        textArea1.setBounds(180, 427, 200, 61);
        getContentPane().add(textArea2);
        textArea2.setBounds(180, 498, 200, 58);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setText("(YYYY/MM/DD)");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(310, 340, 120, 16);

        jLabel17.setText("Ward ID");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(37, 630, 60, 16);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(180, 630, 175, 22);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/app/pdetails.jpg"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(-210, -20, 680, 750);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Reset(){
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField7.setText("");
    jTextField8.setText("");
    jTextField9.setText("");    
    jTextField10.setText("");    
    jTextField11.setText("");
    jTextField12.setText("");
    textArea1.setText("");
    textArea2.setText("");
    jButton3.setEnabled(true);
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  this.setVisible(false);
  new MainPageGUI().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Reset();
try{
    con=Connect.getConnection();
    if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter patient id","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    Statement stmt;
    stmt=con.createStatement();
    String sql1="Select * from patient where P_ID='"+jTextField1.getText() + "'";
    pst=con.prepareStatement(sql1);
    rs=pst.executeQuery();
    if(rs.next()){
        this.setVisible(true);
        String add1=rs.getString("P_ID");
        this.jTextField2.setText(add1);
        String add2=rs.getString("NAME");
        this.jTextField3.setText(add2);
        String add3=rs.getString("GENDER");
        this.jTextField4.setText(add3);
        String add4=rs.getString("ADDRESS");
        this.jTextField5.setText(add4);
        String add5=rs.getString("DATE_ADDED");
        this.jTextField6.setText(add5);
        String add6=rs.getString("DATE_DISCHARGED");
        this.jTextField7.setText(add6);
        String add7=rs.getString("RECOMMENDATION");
        this.jTextField8.setText(add7);
        String add8=rs.getString("CONTACT_NO");
        this.jTextField9.setText(add8);
        String add9=rs.getString("W_ID");
        this.jTextField12.setText(add9);
    }
    String sql2="Select * from patient_treatments where P_ID='"+jTextField1.getText() + "'";
    pst=con.prepareStatement(sql2);
    rs=pst.executeQuery();
    if(rs.next()){
        this.setVisible(true);
        String add1=rs.getString("TESTS");
        this.textArea1.setText(add1);
        this.setVisible(true);
        String add2=rs.getString("RESULTS");
        this.textArea2.setText(add2);
        this.setVisible(true);
        String add3=rs.getString("CONSUL_ID");
        this.jTextField10.setText(add3);
        this.setVisible(true);
        String add4=rs.getString("ADD_CONSUL_ID");
        this.jTextField11.setText(add4);
    }
}catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }
    
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Reset();
jTextField1.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
    con=Connect.getConnection();
    if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter patient id","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    Statement stmt;
    stmt=con.createStatement();
    String sql2="Select P_ID from patient where P_ID='"+jTextField1.getText() + "'";
    rs=stmt.executeQuery(sql2);
    String sql="update patient set DATE_DISCHARGED ='"+jTextField7.getText()+"', W_ID='"+jTextField12.getText()+"'where P_ID='"+jTextField1.getText() + "'";
    pst=con.prepareStatement(sql);
    pst.execute();
    String sql4="Select P_ID from patient_treatments where P_ID='"+jTextField1.getText() + "'";
    rs=stmt.executeQuery(sql4);
    if(rs.next()){
        String sql5="update patient_treatments set TESTS='"+ textArea1.getText() + "'where P_ID='"+jTextField1.getText() + "'";
        pst=con.prepareStatement(sql5);
        pst.execute();
        String sql6="update patient_treatments set RESULTS='"+ textArea2.getText() +"'where P_ID='"+jTextField1.getText() + "'";
        pst=con.prepareStatement(sql6);
        pst.execute();
        String sql7="update patient_treatments set CONSUL_ID='"+ jTextField10.getText() +"'where P_ID='"+jTextField1.getText() + "'";
        pst=con.prepareStatement(sql7);
        pst.execute();
        String sql8="update patient_treatments set ADD_CONSUL_ID='"+ jTextField11.getText() +"'where P_ID='"+jTextField1.getText() + "'";
        pst=con.prepareStatement(sql8);
        pst.execute();
        JOptionPane.showMessageDialog(this,"Successfully saved","Patient Record",JOptionPane.INFORMATION_MESSAGE);
        return;
        
    }
    String sql3= "insert into patient_treatments(P_ID, TESTS, RESULTS, CONSUL_ID ,ADD_CONSUL_ID)values('"+ jTextField1.getText() + "','"+ textArea1.getText() + "','"+ textArea2.getText() + "','"+ jTextField10.getText() + "','"+ jTextField11.getText() + "')";
    pst=con.prepareStatement(sql3);
    pst.execute();
    JOptionPane.showMessageDialog(this,"Successfully saved","Patient Record",JOptionPane.INFORMATION_MESSAGE);
    jButton3.setEnabled(false);
    }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);    
    
}
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.TextArea textArea1;
    private java.awt.TextArea textArea2;
    // End of variables declaration//GEN-END:variables
}
