/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.app;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class User extends javax.swing.JFrame {
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    /**
     * Creates new form User
     */
    public User() {
        initComponents();
        setLocationRelativeTo(null);
        this.setSize(400, 300);
        this.setLocation(350,50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("New User");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(27, 23, 115, 29);

        jLabel2.setText("User ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(27, 73, 80, 16);

        jLabel3.setText("User Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(27, 108, 90, 16);

        jLabel4.setText("Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(27, 143, 80, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(168, 70, 150, 22);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(168, 105, 150, 22);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(168, 140, 150, 22);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(27, 180, 59, 25);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(245, 180, 73, 25);

        jButton3.setText("New");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(149, 180, 57, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/app/healthcare-bg.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-870, -20, 1280, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Reset(){
    jTextField1.setText("");
    jTextField2.setText("");
    jPasswordField1.setText("");
    jButton2.setEnabled(true);
}/*reset*/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.setVisible(false);
new MainPageGUI().setVisible(true);/*back*/
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try{
    con=Connect.getConnection();/*connecting to the database*/
    if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter user id","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    if (jTextField2.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter user name","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    String Password= String.valueOf(jPasswordField1.getPassword());
    if (Password.equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter password","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }/*empty textboxs*/

    Statement stmt;
    stmt=con.createStatement();
    /*selecting the table*/
    String sql1= "select USER_ID from user where USER_ID= '" + jTextField1.getText() + "'";
    rs=stmt.executeQuery(sql1);
    if(rs.next()){
        JOptionPane.showMessageDialog( this, "User ID already exists","Error", JOptionPane.ERROR_MESSAGE);
        jTextField1.setText("");
        return;
    }
    /*creating a new user*/
    String sql="insert into user(USER_ID, USER_NAME, PASSWORD)values('"+jTextField1.getText()+ "','"+jTextField2.getText()+"','"+jPasswordField1.getText()+"')";
    pst=con.prepareStatement(sql);
    pst.execute();
    JOptionPane.showMessageDialog(this,"Successfully saved","User Record",JOptionPane.INFORMATION_MESSAGE);
    jButton2.setEnabled(false);

    }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);

    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Reset();/*reset*/
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
