/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.app;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class WardDetails extends javax.swing.JFrame {
Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form WardDetails
     */
    public WardDetails() {
        initComponents();
        setLocationRelativeTo(null);
        this.setSize(424, 440);
        this.setLocation(350,50);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Ward Details");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(32, 28, 153, 29);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ward ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(32, 82, 84, 16);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(32, 119, 59, 25);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 119, 73, 25);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ward ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(35, 160, 68, 16);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(148, 79, 175, 22);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ward Type");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(35, 186, 84, 16);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ward Doctor ID");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(32, 246, 100, 16);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No. of Beds");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(32, 275, 84, 16);

        jTextField2.setEnabled(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(148, 157, 175, 22);

        jTextField3.setEnabled(false);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(148, 186, 175, 22);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(148, 243, 175, 22);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(148, 272, 175, 22);

        jButton3.setText("Create");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(170, 119, 71, 25);

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(98, 119, 65, 25);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Charge for Bed");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(32, 304, 96, 16);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(148, 301, 175, 22);

        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(148, 356, 73, 25);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ward Type");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(32, 218, 72, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maternity", "Pediatrics", "Oncology", "Gynecologist" }));
        jComboBox1.setSelectedIndex(-1);
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(148, 215, 175, 22);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital/app/First-Western-Hospital-Koh-Phangan-general-ward-1.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-120, -10, 550, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void Reset(){
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jTextField6.setText("");
    jComboBox1.setSelectedIndex(-1);
    jButton5.setEnabled(true);
    jButton3.setEnabled(true);
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  this.setVisible(false);
  new MainPageGUI().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Reset();
jTextField1.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
   try{
    con=Connect.getConnection();    
    if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter ward id","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }

    Statement stmt;
    stmt=con.createStatement();    
    String sql1="Select W_ID from ward where W_ID='"+jTextField1.getText() + "'";
    rs=stmt.executeQuery(sql1);
    if(rs.next()){
        JOptionPane.showMessageDialog( this, "Ward ID already exists","Error", JOptionPane.ERROR_MESSAGE);
        jTextField1.setText("");
        return;
    }
    
    String sql="insert into ward(W_ID, W_TYPE, W_DOCTOR_ID, W_BEDS, B_CHARGE)values('"+jTextField1.getText()+ "','"+jComboBox1.getSelectedItem()+ "','"+jTextField4.getText()+"','"+jTextField5.getText()+"','"+jTextField6.getText()+"')";
    pst=con.prepareStatement(sql);
    pst.execute();
    JOptionPane.showMessageDialog(this,"Successfully saved","Ward Details",JOptionPane.INFORMATION_MESSAGE);
    jButton3.setEnabled(false);
    
    }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);

    }    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
try{
    con=Connect.getConnection();
    if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter ward id","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    
    Statement stmt;
    stmt=con.createStatement();
    String sql2="Select W_ID from ward where W_ID='"+jTextField1.getText() + "'";
    rs=stmt.executeQuery(sql2);
    String sql="update ward set W_TYPE='"+jComboBox1.getSelectedItem()+"', W_DOCTOR_ID='"+jTextField4.getText()+"', W_BEDS='"+jTextField5.getText()+"', B_CHARGE='"+jTextField6.getText()+"'where W_ID='"+jTextField1.getText() + "'";
    pst=con.prepareStatement(sql);
    pst.execute();
    jButton5.setEnabled(false);
    JOptionPane.showMessageDialog(this,"Successfully saved","Ward Details",JOptionPane.INFORMATION_MESSAGE);
    jButton5.setEnabled(true);
    
    }catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(this,ex);    
    
}
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Reset();
try{
    con=Connect.getConnection();
    if (jTextField1.getText().equals("")) {
                JOptionPane.showMessageDialog( this, "Please enter ward id","Error", JOptionPane.ERROR_MESSAGE);
                return;
    }
    Statement stmt;
    stmt=con.createStatement();
    String sql1="Select * from ward where W_ID='"+jTextField1.getText() + "'";
    pst=con.prepareStatement(sql1);
    rs=pst.executeQuery();
    if(rs.next()){
        this.setVisible(true);
        String add1=rs.getString("W_ID");
        this.jTextField2.setText(add1);
        String add2=rs.getString("W_TYPE");
        this.jTextField3.setText(add2);
        String add3=rs.getString("W_DOCTOR_ID");
        this.jTextField4.setText(add3);
        String add4=rs.getString("W_BEDS");
        this.jTextField5.setText(add4);
        String add5=rs.getString("B_CHARGE");
        this.jTextField6.setText(add5);
    }

    }catch(Exception ex){
            JOptionPane.showMessageDialog(this,ex);
        }    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WardDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WardDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WardDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WardDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WardDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
